a = float(input("Enter First Number: "))
b = float(input("Enter Second Number: "))

print("Addition =", a+b)
print("Subtraction =", a-b)
print("Multiplication =", a*b)
print("Division =", a/b)
print("Floor Division =", a//b)
print("Modulus =", a%b)
print("Exponent =", a**b)